### ISSUE TITLE
Settings option crashes application

### ISSUE THREAD

**Issue by ImmutableGlitch** [Anathena/Anathena#179]
Edit>Settings causes the application to crash. 

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	Ana.exe
  Problem Signature 02:	3.4.4.0
  Problem Signature 03:	587c26ca
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.6.1590.0
  Problem Signature 06:	5787ee1b
  Problem Signature 07:	fa4
  Problem Signature 08:	5c
  Problem Signature 09:	System.Windows.Markup.XamlParse
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	2057
  Additional Information 1:	ff39
  Additional Information 2:	ff393bcb7a1b6520af1f09609bd862be
  Additional Information 3:	1925
  Additional Information 4:	1925ea8641f3c11147bbf30579ec6665

**Comment by zcanann** [comment]
Fixed that recently in https://github.com/Anathena/Anathena/commit/a38bd2732b83ccbe7b6cc7e293dee0e2fbd1ea00

The issue was my conversions not handling 0 properly due to some recent changes, so when the base address is set to '0' (which it almost always will be), it caused a crash.

When I put out the next release this should be resolved
