### ISSUE TITLE
UI feedback for textbox

### ISSUE THREAD

**Issue by ImmutableGlitch** [Anathena/Anathena#180]
The textbox for the Manual Scanner gives no visual feedback when clicked. Could show flashing keyboard cursor or colour change

**Comment by zcanann** [comment]
There is a mix of WinForms and WPF in this project in certain places, and these textboxes are one of them.

I wrote the textbox back when this project was 100% WinForms, and it has a lot of nice features (being able to right click and convert to hex, text coloring).

I'll try and look into a solution, otherwise it will have to wait until I recreate the textbox in WPF with the same features.

**Comment by ImmutableGlitch** [comment]
As a beginner, I was wondering if there are any smaller issues with Anathena that I could work on?

**Comment by zcanann** [comment]
As for smaller issues, there aren't a lot. The only one that immediately comes to mind is this:

![broken](https://cloud.githubusercontent.com/assets/5906208/22319567/cf4486e8-e338-11e6-908a-2702284a7f35.PNG)

If you have two monitors and open this menu (red line indicates where monitors join), it can cause some weird positional glitches. It's pretty minor so I've just ignored it for now.
